apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend-app
  template:
    metadata:
      labels:
        app: my-backend-app
    spec:
      containers:
      - name: backend-container
        image: alamzia23/nodejs-blog:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://alamziyafzd:8I24Qyhwg5X7hv6G@cluster0.ffzdu.mongodb.net/"
        - name: JWT_SECRET
          value: "MySecretBlog"
