apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hbGFteml5YWZ6ZDoxSDI0UXlod2c1WDdodjZHQGNsdXN0ZXIwLmZmemR1Lm1vbmdvZGIubmV0Lw==
  JWT_SECRET: TXlTZWNyZXRCbG9n
